function [p, perfil, referencias] = preparar_martinete()
%PREPARAR_MARTINETE Carga datos, genera geometria y valida referencias.

[p, perfil] = martinete_parametros();
generatedDir = fullfile(fileparts(mfilename("fullpath")), "generated");
p.camStlPath = generar_stl_leva(perfil, p, ...
    fullfile(generatedDir, "leva_balistica_12lb.stl"));

referenceSpeeds = unique([30; 40; 50; 65; 70; 80; p.simulationRpm]);
referencias = calcular_referencias(p, perfil, referenceSpeeds);

fprintf("Perfil: %d puntos CSV, %d puntos de contacto.\n", ...
    height(perfil.table), size(perfil.contact_xy_m, 1));
fprintf("Radio fisico: %.1f a %.1f mm; mu max: %.2f deg.\n", ...
    perfil.metrics.baseRadius_m * 1e3, ...
    perfil.metrics.maxRadius_m * 1e3, ...
    rad2deg(perfil.metrics.maxPressureAngle_rad));
fprintf("Desvio estandar del circulo base: %.6f mm.\n", ...
    perfil.metrics.baseRadiusStd_m * 1e3);
fprintf(['Toma C2 monotona: %.1f deg previos + %.1f deg de subida, ' ...
    'radio %.3f a %.3f mm, ' ...
    '|dr/dalpha| max %.2f mm/rad.\n'], ...
    rad2deg(perfil.metrics.pickupBlendAngle_rad), ...
    rad2deg(perfil.metrics.pickupJoinRiseAngle_rad), ...
    perfil.metrics.pickupRadiusStart_m * 1e3, ...
    perfil.metrics.pickupRadiusEnd_m * 1e3, ...
    perfil.metrics.pickupMaxRadialSlope_m_rad * 1e3);
fprintf(['Pose inicial mundial: theta=%.1f deg, cara de golpe y=%.3f mm, ' ...
    'piso y=%.3f mm.\n'], ...
    rad2deg(p.worldTheta0), ...
    1e3 * (p.pivotHeight - p.headContactOffset - ...
    p.headContactRadius), ...
    1e3 * p.groundInitialY);
fprintf(['Cuerpos rigidos: cabeza %.3f kg, mango %.3f kg, palanca gris ' ...
    '%.3f kg, rodillo/eje %.3f kg; contacto 3D activo y holgura axial ' ...
    '%.1f mm.\n'], ...
    p.headMass, p.handleShaftMass, p.bellCrankMass, ...
    p.rollerMass + p.rollerAxleMass, ...
    1e3 * p.camLeverAxialClearance);

nominal = referencias(referencias.rpm == p.nominalRpm, :);
fprintf(['A 65 rpm: omega_rel=%.3f rad/s, apice=%.2f deg, ' ...
    'E=%.2f J, t_caida=%.3f s, margen=%.1f%%.\n'], ...
    nominal.omegaRelease_rad_s, rad2deg(nominal.thetaApex_rad), ...
    nominal.impactEnergy_J, nominal.fallTime_s, ...
    100 * nominal.timeMargin);
fprintf(['Tiempo real disparo-impacto=%.3f s; margen hasta la proxima ' ...
    'vuelta=%.1f%%.\n'], nominal.releaseToImpactTime_s, ...
    100 * nominal.fullCycleMargin);
if nominal.fullCycleMargin < 0
    warning("Martinete:ReenganchePrematuro", ...
        ['A %.0f rpm la leva completa el sector de caida antes de que ' ...
        'el martillo impacte. La comparacion original omite el ascenso ' ...
        'balistico desde el disparo hasta el apice.'], p.nominalRpm);
end

simulationCase = referencias(referencias.rpm == p.simulationRpm, :);
fprintf(['Caso multivuelta: %.0f rpm, %d vueltas, piso 0 a -%.0f mm, ' ...
    'compactacion activada por F > %.0f N, margen balistico %.1f%%.\n'], ...
    p.simulationRpm, p.simRevolutions, p.groundMaxSink * 1e3, ...
    p.soilYieldForce, ...
    100 * simulationCase.fullCycleMargin);

assignin("base", "p", p);
assignin("base", "perfil", perfil);
assignin("base", "referencias", referencias);
end
