function reporte = validar_martinete()
%VALIDAR_MARTINETE Regresion analitica contra la tabla de especificacion.

[p, perfil] = martinete_parametros();
referencias = calcular_referencias(p, perfil, p.nominalRpm);
nominal = referencias(1, :);

sectorTime = (2 * pi - p.dphiRise) / (2 * pi) * ...
    60 / p.nominalRpm;
actual = [ ...
    2 * pi * p.nominalRpm / 60; ...
    nominal.kRel; ...
    nominal.omegaRelease_rad_s; ...
    rad2deg(nominal.thetaApex_rad); ...
    nominal.impactEnergy_J; ...
    nominal.impactSpeed_m_s; ...
    nominal.fallTime_s; ...
    sectorTime; ...
    nominal.peakCamTorque_Nm; ...
    nominal.meanCamTorque_Nm; ...
    nominal.peakRollerForce_N];
expected = [6.807; 0.3556; 2.42; 31.6; 39.1; 3.69; ...
    0.395; 0.462; 24.5; 12.5; 331];
names = ["omega_cam_rad_s"; "k_rel"; "omega_rel_rad_s"; ...
    "theta_apex_deg"; "energia_J"; "velocidad_cabeza_m_s"; ...
    "tiempo_caida_s"; "tiempo_sector_s"; "par_pico_Nm"; ...
    "par_medio_Nm"; "fuerza_rodillo_N"];

relativeError = abs(actual - expected) ./ abs(expected);
passes = relativeError <= 0.01;

% El margen publicado esta redondeado a 17 %, por lo que se verifica con
% tolerancia absoluta. Se informa aparte el margen fisico completo.
marginPublished = 0.17;
marginPasses = abs(nominal.timeMargin - marginPublished) <= 0.005;

reporte = table(names, expected, actual, relativeError, passes);
disp(reporte);
fprintf("Margen publicado: esperado 0.170, calculado %.5f -> %s.\n", ...
    nominal.timeMargin, string(marginPasses));
fprintf("Margen fisico disparo-impacto: %.1f %%.\n", ...
    100 * nominal.fullCycleMargin);

assert(all(passes), ...
    "Martinete:RegresionFallida", ...
    "Una o mas referencias nominales exceden el 1 %% de error.");
assert(marginPasses, ...
    "Martinete:RegresionMargenFallida", ...
    "El margen publicado no coincide con la especificacion.");
assert(perfil.metrics.baseRadiusStd_m < 1e-5, ...
    "Martinete:CirculoBaseInvalido", ...
    "El radio del sector de caida no es constante dentro de 0.01 mm.");
assert(perfil.metrics.pickupPositionError_m < 1e-10, ...
    "Martinete:EmpalmeTomaC0", ...
    "La transicion de toma no es continua en posicion.");
assert(perfil.metrics.pickupSlopeError_m_rad < 1e-10, ...
    "Martinete:EmpalmeTomaC1", ...
    "La transicion de toma no es continua en pendiente.");
assert(perfil.metrics.pickupCurvatureError_m_rad2 < 1e-10, ...
    "Martinete:EmpalmeTomaC2", ...
    "La transicion de toma no es continua en curvatura.");
pickupRadius = vecnorm(perfil.pickup_xy_m, 2, 2);
assert(all(diff(pickupRadius) >= -1e-12), ...
    "Martinete:EmpalmeTomaNoMonotono", ...
    "El radio de la transicion de toma contiene un maximo local.");
initialHeadFaceY = p.pivotHeight + ...
    p.Lh * sin(p.worldTheta0) - ...
    p.headContactOffset * cos(p.worldTheta0) - ...
    p.headContactRadius;
assert(abs(p.worldTheta0) < 1e-12, ...
    "Martinete:AnguloInicialNoHorizontal", ...
    "La maza debe comenzar horizontal en la referencia mundial.");
assert(abs(initialHeadFaceY - p.groundInitialY) < 1e-12, ...
    "Martinete:ContactoInicialFueraDePiso", ...
    "La cara inferior de la cabeza debe comenzar exactamente en y=0.");
end
